-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgN/mwRbjgoQNh23Nz
FC3PM2sG1dPXrtnBJecqi0eAoVugCgYIKoZIzj0DAQehRANCAAR+7uMLOdwHqNmw
wKPy9uXAqFALIa7tUZgfjWfkUk0BlhDCOhlCyhD7WHhQmq5bT4NncipNtbFiJWX8
YjUnJtzo
-----END PRIVATE KEY-----